version: "3.8"
services:
  #  db:
  #    container_name: "gocr-db"
  #    image: postgres:12
  #    environment:
  #      POSTGRES_USER: app
  #      POSTGRES_PASSWORD: 123
  #    ports:
  #      - 5432:5432
  #    volumes:
  #      - type: bind
  #        source: ./data
  #        target: /var/lib/postgresql/data
  server:
    container_name: "gocr-server"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      AUTH0_API_IDENTIFIER: "http://gocr-api"
      AUTH0_DOMAIN: "localhost:4242"
    healthcheck:
      test:
        ["CMD-SHELL", "curl -sSf GET localhost:4242/gocr/healthy > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "4242:4242"
    #    depends_on:
    #     - db
    restart: always
