version: "3.8"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
